before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HBcZSLEtW0EpW1g/EkC5221L7tPfkJlG431QRwwqEw8bQBChOcni2jbWcTthYjRCTXne8MYKjJCfjfHb2YPAtrtzOPt3hrQLtdy/bhrv4f6JHtqluiwbSN+3vuJbEav8FgoK8AoukYV4sHel4o819DOi9TTT7+wFZZ6TyGlXqCrC2g3Wpn0CXOaODhRnaSBEof2rPHrOdwVfyLlQZDFh/tmWYoTPPZXsKCM84RTf5MA2Jycf9TIScfYSDph1d6FoR+yGVJ27e0Ted+PFEf0BiqnAxttY8nAt8SM6PiqQIcz0QiPc5JCrvU/MKh5jIyh5vO236b0dceqRhpzr94CokaVMuMrvRZQJYuUM9zAkhoqqgPLxbgwLHwjVPwOvu9ki7N+tf8JfpELomW6MH1Wr7xbEwRwQPCH5JiP2ov3de+S8n5adV4UqYLn4hL3allpIb+S5BQVfvDoHKCBul3j+qFjIXjtac9x7EB0DFq63o/jdv/ayK3vUT3/pIDdSYb4ax+i2JKEQeCRMYyMOz4NBJgT/Ol46RbD+cBOHrQkAxoHcvZu62+zS+RobWdngEyE39PIux/PQChhOkKPCBu6BzTqPO4kpM37PaHjN0rE3H59CG3weJVf9ZVNDlGq1eVpZ4IiQZ1JrAPs9cpR2G/L7EiC5Cm1dIdAwMxqsUxCqXq4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
